name: 'Merge Dependencies'

on:
  pull_request:

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    steps:
      - uses: actions/checkout@v6
      - uses: ahmadnassri/action-dependabot-auto-merge@v2.6.6
        with:
          github-token: ${{ secrets.AUTOMERGE_TOKEN }}
          # Merge all updates (major, minor, and patch) as long as they pass CI
          update_type: "semver:major" 
